# Generated by Django 4.1.5 on 2023-02-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='phone',
        ),
    ]
