# Generated by Django 4.1.5 on 2023-02-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_detail_email_remove_detail_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='name',
            new_name='firstname',
        ),
    ]
