# Generated by Django 4.1.5 on 2023-12-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_name_detail_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='contact',
            field=models.IntegerField(default='Contact', max_length=100),
        ),
    ]
