# Generated by Django 4.1.5 on 2023-12-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_detail_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='contact',
            field=models.CharField(default='contact-update', max_length=100),
        ),
    ]
