# Generated by Django 4.1.5 on 2023-12-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_detail_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
