# Generated by Django 4.1.5 on 2023-12-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='phone',
        ),
        migrations.AddField(
            model_name='detail',
            name='contact',
            field=models.IntegerField(default='contact'),
        ),
    ]
