# Generated by Django 4.1.5 on 2023-12-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
