# Generated by Django 4.1.5 on 2024-01-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='phone',
            field=models.CharField(default='phone', max_length=100),
        ),
    ]
