# Generated by Django 4.1.5 on 2024-01-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_detail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='phone',
            field=models.IntegerField(default='phone1', max_length=100),
        ),
    ]
