# Generated by Django 4.1.5 on 2024-01-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_detail_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
