# Generated by Django 4.1.5 on 2024-01-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='phone',
        ),
    ]
